<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="PF35M749" failures="0" tests="4" name="LoginTest Error" time="1.016" errors="0" timestamp="2023-03-19T12:36:03 CET">
  <testcase classname="TestCollection" name="loginWithUsernameAndPassword" time="0.282"/>
  <testcase classname="TestCollection" name="loginWithUsernameAndPassword" time="0.177"/>
  <testcase classname="TestCollection" name="loginWithUsernameAndPassword" time="0.157"/>
  <testcase classname="TestCollection" name="loginWithUsernameAndPassword" time="0.195"/>
  <testcase classname="TestCollection" name="createNewConnectionAndValidateStats" time="0.0">
    <ignored/>
  </testcase> <!-- createNewConnectionAndValidateStats -->
  <testcase classname="TestCollection" name="createNewConnection" time="0.0">
    <ignored/>
  </testcase> <!-- createNewConnection -->
  <testcase classname="TestCollection" name="loginWithCorrectUsernameAndPassword" time="0.0">
    <ignored/>
  </testcase> <!-- loginWithCorrectUsernameAndPassword -->
</testsuite> <!-- LoginTest Error -->
